language: java
sudo: false

env:
  - ossrhNexusUser=nothing
  - ossrhNexusPassword=nothing
cache:
  directories:
  - $HOME/.gradle
jdk:
  - oraclejdk8
  - openjdk7

install: ./gradlew clean build
script: ./gradlew clean test
