language: java
sudo: false

cache:
  directories:
  - $HOME/.gradle
jdk:
  - oraclejdk8
  - openjdk7

install:
  - mkdir -p ~/.gradle/
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - echo "ossrhNexusUser=null" >> ~/.gradle/gradle.properties
  - echo "ossrhNexusPassword=null" >> ~/.gradle/gradle.properties

script:
  - ./gradlew clean build
  - ./gradlew test
